title: Kelleher Logs
description: Notes from current software projects and experiments.
url: "https://tkellehe.github.io"
baseurl: ""
timezone: America/New_York

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-last-modified-at

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

github_url: "https://github.com/tkellehe/"
linkedin_url: "https://www.linkedin.com/in/mitchell-kelleher/"
repository_url: "https://github.com/tkellehe/tkellehe.github.io"
repository_branch: "main"
copyright_name: "Mitchell Kelleher"
content_license: "CC BY 4.0"
